###

GET http://localhost:3031/

###

GET http://localhost:3031/users

###

POST  http://localhost:3031/signup
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN 

{
	"username" : "janota",
	"email": "janota@epicsteam.com",
	"passwd": "cenoura"
}

###

POST  http://localhost:3031/signin
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN 

{
	"username" : "native",
	"passwd": "cenoura"
}

###

